export default {
    BLOCK_DIM: 20,
    PLAYER_BLOCK: 16,
    MAX_SHADOW_PERC: .25,
    PLAYER_SPEED: 1,
    RAY_SPACE: .01,
    RAY_AMOUNT_ONE_SIDE: 50,
    RAYS_SKIPPED_TO_DRAW_2D: 20,
    MAP_WIDTH: 25,
    MAP_HEIGHT: 25,
}